name: CI

on:
  pull_request:
    branches:
      - develop
  push:
    branches:
      - develop

jobs:
  ci:
    name: CI
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2

      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: 10.x

      - name: Cache
        uses: actions/cache@v1
        with:
          path: ~/.cache/yarn
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: ${{ runner.os }}-yarn-

      - name: Install
        run: yarn --frozen-lockfile

      - name: Build
        run: yarn build

      - name: Deploy
        if: ${{ github.ref == 'refs/heads/develop' }}
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: master
          publish_dir: ./out
